version: '2'
services:

  pyapp:
    build:
      context: ./backend/eureka
    ports:
     - "8000:8000"
    environment:
      DOCKER_CONTAINER: "true"
      POSTGRES_PASS: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_NAME: postgres
    depends_on:
    - "postgres"

  isd:
    build: ./sample-data
    command: ./create-data.sh
    environment:
      PGPASSWORD: postgres

  ngapp:
    build:
      context: ./frontend/eureka
    ports:
     - "3000:3000"
    environment:
      BACKEND_URL: "pyapp"


  redis:
    image:  sameersbn/redis:latest 
    ports:
     - "6379:6379"
    volumes:
    - ./data:/data
    environment: 
      REDIS_PASSWORD: 1A2S3D4F5G
  postgres:
    image: "postgres"
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres


  image:
    build:
      context: ./backend/image
    ports:
     - "8001:5000"
