version: '2'
services:

  pyapp:
    build:
      context: ./backend/eureka
    ports:
     - "8000:8000"
    volumes:
     - ./backend/eureka:/code
    environment:
      DOCKER_CONTAINER: "true"
      POSTGRES_PASS: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_NAME: postgres
    depends_on:
    - "postgres"


  ngapp:
    build:
      context: ./frontend/eureka
    ports:
     - "3000:3000"
    volumes:
     - ./frontend/eureka:/code
    environment:
      BACKEND_URL: "pyapp"

  postgres:
    image: "postgres"
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres


  image:
    build:
      context: ./backend/image
    ports:
     - "8001:5000"
    volumes:
     - ./backend/image:/code
