swagger: "2.0"
info:
  description: "This is the API documentation of the EUREKA project."
  version: "1.0.0"
  title: "Eureka Living History API"
  termsOfService: "TBA"
  contact:
    email: "TBA@TBA.com"
  license:
    name: "MIT"
    url: "https://github.com/SWE574-Nerds/friendly-eureka/blob/master/LICENSE.md"
basePath: "/api/v1/"
tags:
- name: "Eureka"
- name: "Living"
- name: "History"
schemes:
- "http"
