# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0002_annotation_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='motivation',
            field=models.TextField(default='', verbose_name='Motivation'),
            preserve_default=False,
        ),
    ]
