# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0003_annotation_motivation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='motivation',
        ),
    ]
